// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEneb55Fe7ANdZmU2VvqXzG6V8pJkQwsM',
    appId: '1:123435358107:web:c72022e5398a1bbe65f33e',
    messagingSenderId: '123435358107',
    projectId: 'things-collector',
    authDomain: 'things-collector.firebaseapp.com',
    storageBucket: 'things-collector.firebasestorage.app',
    measurementId: 'G-Y5HM0BRY6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJNhuB7cLdJAXOfRTrJmfl5i2JyLrGzY',
    appId: '1:123435358107:android:3b52de52d59829bf65f33e',
    messagingSenderId: '123435358107',
    projectId: 'things-collector',
    storageBucket: 'things-collector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CM9Yu2U8v8LfeqfDdCcbbv5EI-8Dvc0',
    appId: '1:123435358107:ios:5f9e1bf81a5d706c65f33e',
    messagingSenderId: '123435358107',
    projectId: 'things-collector',
    storageBucket: 'things-collector.firebasestorage.app',
    iosBundleId: 'com.example.thingsCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CM9Yu2U8v8LfeqfDdCcbbv5EI-8Dvc0',
    appId: '1:123435358107:ios:5f9e1bf81a5d706c65f33e',
    messagingSenderId: '123435358107',
    projectId: 'things-collector',
    storageBucket: 'things-collector.firebasestorage.app',
    iosBundleId: 'com.example.thingsCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEneb55Fe7ANdZmU2VvqXzG6V8pJkQwsM',
    appId: '1:123435358107:web:bc72837d38c264a465f33e',
    messagingSenderId: '123435358107',
    projectId: 'things-collector',
    authDomain: 'things-collector.firebaseapp.com',
    storageBucket: 'things-collector.firebasestorage.app',
    measurementId: 'G-HYCEB8D4LE',
  );
}
